# Generated by Django 4.1.7 on 2023-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('a', 'fundacja'), ('b', 'organizacja pozarządowa'), ('c', 'zbiórka lokalna'), ('d', 'domyślnie fundacja')], max_length=1)),
            ],
        ),
    ]
