# Generated by Django 4.0.2 on 2023-03-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_project', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
