# Generated by Django 4.0.2 on 2023-03-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_project', '0006_categoriesinst_categoriesdonation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name_plural': 'Institutions'},
        ),
    ]
